spring:
  jackson:
    date-format:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
debug: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: classpath:pers.goetboy.*.model.entity
server:
  port: 8080

